apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: users
commonLabels:
  app: users-service
resources:
- namespace.yaml
- deployment.yaml
- ingressroute.yaml
- middlewares/users-stripprefix.yaml
- service.yaml

configurations:
  - transformers/namespace.yaml
